name: Send daily notifications

on:
  schedule:
    # Should run at 8, 14, 17h (UTC-3) except on weekends
    - cron: "0 11,17,20 * * MON-FRI"

jobs:
  daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call daily callback
        run: echo 'deprecated'